### ISSUE TITLE
Pinned challenges

### ISSUE THREAD

**Issue by fenske** [fenske/devskills-app#111]
As a user, I want to be able to pin favorite challenges on the Library view. This will let me save time inviting new candidates as I oftentimes use the same challenges.

### Acceptance Criteria

- [x] There's a way to pin a challenge so that it appears at the top of the lib list (could be done via a toggle on the challenge slideover).
- [x] All pinned challenges appear at the top of the list for easy access. Consider using the ["Simple Cards" component](https://tailwindui.com/components/application-ui/lists/grid-lists#component-4ec337def61b547035ce908c128bca5c) from TailwindUI. Wrap pins when overflowed.
- [x] Clicking on a pinned challenge should open the selected challenge's slideover.
- [x] There should be a way to remove a challenge from the pinned. See the pop-up menu of the "simple cards".

**Comment by fenske** [comment]
## Grooming

### Data model changes

Introduce a new `pinnedChallenges: string[]` field on the org doc. This array would consist of uid's of the corresponding challenge docs from the org `challenges` collection.

![CleanShot 2021-05-17 at 11 09 33](https://user-images.githubusercontent.com/1162212/118463743-6823ed00-b700-11eb-803b-a017e50602e4.png)

**Comment by fenske** [comment]
@Safi-Ullah Your PR for this ticket has been released. Great job! 👏 

Feel free to share the time spent in a comment below.

**Comment by Safi-Ullah** [comment]
Thanks.....it took me approx. 15 hrs to get this task done.
