### ISSUE TITLE
Email notifications for candidate state updates

### ISSUE THREAD

**Issue by fenske** [fenske/devskills-app#217]
As a user, I want to watch candidate's state changes and receive email notifications for each change.

### Acceptance Criteria

- [x] There should be an option for the user to "watch" the candidate which would effectively sign them up for email updates for each state change for that candidate.
- [x] Whenever a candidate changes its `state` a corresponding email is sent to all watchers.
- [x] Whenever a user invites a candidate, they automatically become the watcher of that candidate.
- [x] Create the necessary composite indexes in prod

**Comment by fenske** [comment]
### Grooming

- [ ] Email copy

**Comment by fenske** [comment]
@Safi-Ullah, this one would be the next one to pick up.

**Comment by Safi-Ullah** [comment]
> @Safi-Ullah, this one would be the next one to pick up.

Yeah, I know I've started with this one.

**Comment by fenske** [comment]
Great! 💫 Feel free to move the tickets on the board too when started. ☺️

**Comment by Safi-Ullah** [comment]
> ##### Email copy
> ```
> A new candidate change has occurred:<br/><br/>
> <ul>
>   <li>Candidate: ${candidateName ?? candidateGithubUsername} (${candidateEmail})</li>
>   <li>Challenge: ${challengeName}</li>
>   <li>Old state: ${oldState}</li>
>   <li>New state: ${newState}</li>
> </ul> 
> 
> <br/><br/>
> You can unsubscribe from the state changes for this candidate via the <a href="https://app.devskills.co/candidates" target="_blank">Candidate view in the web app.</a>.<br/><br/>
> 
> Best,<br/>
> <a href="https://devskills.co" target="_blank">DevSkills</a>.
> ```

I don't think we have the candidate's name to address him in the mail. All we require for inviting a candidate is their email, no name.

**Comment by fenske** [comment]
It's fetched from their GitHub profile when they access their invite.

Sometimes it might be missing though, hence the "??".

**Comment by fenske** [comment]
Just released and tested in prod. ✅ 

Good job, @Safi-Ullah ! 👏

**Comment by Safi-Ullah** [comment]
> @Safi-Ullah Wanted to note down some data points for my grooming system.
> 
> Would you mind sharing your time investment for this task?
Yeah, sure....It took me about 9 hrs to get this task done.
