### ISSUE TITLE
Sort lib challenges alphabetically

### ISSUE THREAD

**Issue by fenske** [fenske/devskills-app#227]
As a user, I want to see challenges sorted alphabetically on the library view.

### AC
Whenever the library is loaded, the challenges appear in the alphabetical order.

**Comment by fenske** [comment]
### Grooming

The challenge list has to be sorted alphabetically by [this point](https://github.com/fenske/devskills-app/blob/97dfa9da13d302ee2fb04a195c66e4e05ac1bcb3/components/library/Library.tsx#L75).

It shouldn't crash on corner cases (e.g. the list is empty).

Good to have a unit test for the sorting function itself (unless using a function from a lib).

**Comment by Safi-Ullah** [comment]
> The challenge list has to be sorted alphabetically by [this point](https://github.com/fenske/devskills-app/blob/97dfa9da13d302ee2fb04a195c66e4e05ac1bcb3/components/library/Library.tsx#L75).

Wouldn't it be better to sort simply while retrieving the list from Firestore using `orderBy`, rather than sorting here?

**Comment by fenske** [comment]
> > The challenge list has to be sorted alphabetically by [this point](https://github.com/fenske/devskills-app/blob/97dfa9da13d302ee2fb04a195c66e4e05ac1bcb3/components/library/Library.tsx#L75).
> 
> Wouldn't it be better to sort while retrieving the list from Firestore using `orderBy`, rather than sorting here?

Good point. It's totally better. 👍

**Comment by fenske** [comment]
@Safi-Ullah Just realized that we should probably do two levels of sorting:

1. Alphabetically by profile.
2. Within each profile, alphabetically by challenge name.

E.g.

Backend - Broker API
Backend - Streaming Service
Frontend - Movie App
Frontend - Vending Machine App

Makes sense?

**Comment by Safi-Ullah** [comment]
Yeah, I understand what you mean.

**Comment by fenske** [comment]
@Safi-Ullah As usual, what was your time investment? :)

**Comment by Safi-Ullah** [comment]
It took me about 30 mins, I guess.
