### ISSUE TITLE
Pagination for the lib view

### ISSUE THREAD

**Issue by fenske** [fenske/devskills-app#228]
As a user, I want the challenge library view to be paginated instead of having one very long list.

### AC
- Complete the implementation the same way it was done for the candidate board in #214

**Comment by fenske** [comment]
### Grooming

Just replicate the work which has been done in #214.

**Comment by fenske** [comment]
### Grooming

The challenge list has to be sorted alphabetically by [this point](https://github.com/fenske/devskills-app/blob/97dfa9da13d302ee2fb04a195c66e4e05ac1bcb3/components/library/Library.tsx#L75).

It shouldn't crash on corner cases (e.g. the list is empty).

Good to have a unit test for the sorting function itself (unless using a function from a lib).

**Comment by fenske** [comment]
Shipped. 🚀  

@Safi-Ullah Would you share your time investment for this one?

**Comment by Safi-Ullah** [comment]
> @Safi-Ullah Would you share your time investment for this one?

It took around 30 mins.

**Comment by fenske** [comment]
Nice thanks!
