### ISSUE TITLE
In-app candidate page

### ISSUE THREAD

**Issue by fenske** [fenske/devskills-app#229]
### User Story

As a user, I want all candidate assignment's information to be available on a separate webpage.

### AC

- The candidate slideover turns into a separate candidate page with all relevant information.
- Each candidate's page should have its' own unique URL (`/candidates/{candidate_id}` where `candidate_id` is an external candidate's ID of type UUIDv4. Create an `id` field for that).

### Candidate page mockup

![mockup](https://user-images.githubusercontent.com/1162212/121902269-737e2e80-cd27-11eb-96fc-fa4157028ada.png)

Use [this TailwindUI example](https://tailwindui.com/components/application-ui/page-examples/detail-screens#component-80034b9052ca551c25f7d731b7b3c6dd) to assemble it.

**Comment by fenske** [comment]
### Grooming

#### Work to be done

1. Implement a design.
2. Backfill the new `id` field across all docs under the `assignments` collections.
3. Implement the logic for the new candidate page.
4. Deprecate the old candidate slideover.
5. Write tests where appropriate.

**Comment by fenske** [comment]
@Safi-Ullah here's the next one. 🙋‍♂️ Let me know in case of any questions.

**Comment by Safi-Ullah** [comment]
> Each candidate's page should have its' own unique URL (/candidates/{candidate_id} where candidate_id is an external candidate's ID of type UUIDv4. Create an id field for that).

I get that we can assign an `id` while sending a challenge from now on...but how'll we assign ids for existing assignments.

**Comment by fenske** [comment]
> > Each candidate's page should have its' own unique URL (/candidates/{candidate_id} where candidate_id is an external candidate's ID of type UUIDv4. Create an id field for that).
> 
> I get that we can assign an `id` while sending a challenge from now on...but how'll we assign ids for existing assignments.

You'll need to write a script that will backfill those with random values. That script will use [firebase admin](https://www.npmjs.com/package/firebase-admin).

You'll import it like so:

```
const admin = require("firebase-admin");

const serviceAccount = require("../serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://devskills-dev.firebaseio.com"
});

const db = admin.firestore();
...
```

And to download `serviceAccountKey.json`, go [here](https://console.firebase.google.com/project/devskills-dev/settings/serviceaccounts/adminsdk).

**Comment by fenske** [comment]
@Safi-Ullah Closing this issue, so need to tag it with sizing. 

What was your time investment, if I may ask?

**Comment by Safi-Ullah** [comment]
> What was your time investment, if I may ask?

I spent around 12 hrs on this.
