### ISSUE TITLE
Extend the candidate overview with auto-test results

### ISSUE THREAD

**Issue by fenske** [fenske/devskills-app#235]
### User Story

As a user, I want to be able to see the auto-test results on the candidate overview page.

### AC

- Whenever there is the `autoScore` field on the assignment doc, the corresponding candidate page should include detailed results of the auto-tests (See mockup below). Hide the corresponding region otherwise.
- Parse the data under `autoScore` to render the table
- Use the redacted version of the list from [this TailwindUI example](https://tailwindui.com/components/application-ui/page-examples/home-screens#component-d222be82dfec1951191abe8624a2a1ed) to render the test results.
- Use the logic similar to [ChallengeStatus](https://github.com/fenske/devskills-app/blob/master/components/candidateList/ChallengeStatus.tsx#L3) to color the total auto-score badge.
- Round all regions with the same radius as the enclosing region.

**Comment by fenske** [comment]
### Grooming

#### Mockup

![CleanShot 2021-06-28 at 13 47 17](https://user-images.githubusercontent.com/1162212/123631768-68db9300-d817-11eb-899c-9a500be0ea42.png)

Please note some labels got renamed:

- Results -> Code review
- Seel all results -> See results

**Comment by fenske** [comment]
@Safi-Ullah This would be the next task.

**Comment by Safi-Ullah** [comment]
> * Whenever there is the `autoScore` field on the assignment doc, the corresponding candidate page should include detailed results of the auto-tests (See mockup below). Hide the corresponding region otherwise.
> * Parse the data under `autoScore` to render the table

Currently, I don't see any `autoScore` field on the assignment doc. Can you add a few as a sample for me to parse the data and render as a table.

**Comment by fenske** [comment]
Here's an example:

<img width="503" alt="CleanShot 2021-07-01 at 22 49 50@2x" src="https://user-images.githubusercontent.com/1162212/124187862-b7f72180-dabe-11eb-8790-cbbd90d1d571.png">

To replicate:

1. Configure ngrok as it says in the Readme and add the host as base url.
2. Create a new candidate
3. Create a new branch on that candidate's repo (that will start a new build, and make GitHub push the results)
4. Check the corresponding assignment doc on Firestore.

**Comment by fenske** [comment]
If you could share your time investment here, I'd appreciate it.

**Comment by Safi-Ullah** [comment]
> @Safi-Ullah If you could share your time investment here, I'd appreciate it.

Sure, It took me around 5hrs to get this done.

**Comment by fenske** [comment]
Thanks! It's in production. Looking great! 

<img width="1222" alt="CleanShot 2021-07-06 at 16 16 50@2x" src="https://user-images.githubusercontent.com/1162212/124615515-a377a800-de75-11eb-889e-1818d3441984.png">
