### ISSUE TITLE
Full in-app scorecards

### ISSUE THREAD

**Issue by fenske** [fenske/devskills-app#239]
### User Story

As a user, I want to be able to edit the code review scorecard in-app.

### Mockup 1

![CleanShot 2021-07-07 at 14 30 19](https://user-images.githubusercontent.com/1162212/124760555-2578d700-df31-11eb-94e8-c649633a3ad4.png)

### Mockup 2

![CleanShot 2021-07-07 at 14 40 17](https://user-images.githubusercontent.com/1162212/124760829-6c66cc80-df31-11eb-8e7b-a25ea5213434.png)

### Mockup 3

![CleanShot 2021-07-07 at 14 41 53](https://user-images.githubusercontent.com/1162212/124760989-9a4c1100-df31-11eb-8f60-285a64ed189d.png)

**Comment by fenske** [comment]
### TODO

- [ ] Data model changes

**Comment by fenske** [comment]
@Safi-Ullah Here's the next story to pick up (a logical continuation of your previous task). 😃 

This one is a bit bulkier, so please let me know if anything is unclear so that we can hash it out early.

**Comment by Safi-Ullah** [comment]
As mentioned in mock 3 that `Scoring criteria` should be visible on hovering the icon but `headless-ui` doesn't provide a hover option for `Popover` right out of the box.

I found a solution to the problem [here](https://github.com/tailwindlabs/headlessui/issues/239#issuecomment-850718610), should I go for it..?

**Comment by fenske** [comment]
> As mentioned in mocks 2 and 3 that `Scoring criteria` should be visible on hovering the icon but `headless-ui` doesn't provide a hover option for `Popover` right out of the box.
> 
> I found a solution to the problem [here](https://github.com/tailwindlabs/headlessui/issues/239#issuecomment-850718610), should I go for it, or would clicking on the icon work..?

Looks good to me. 👍  So feel free to go for it.

**Comment by fenske** [comment]
@Safi-Ullah In parallel, I'm working on optimizing the way for how we provision challenge updates across the orgs, and that introduced slight changes to how scorecards will be stored in Firestore:

![CleanShot 2021-07-13 at 15 17 01@2x](https://user-images.githubusercontent.com/1162212/125458635-485268b7-97a1-4432-99a8-ea4f54db9de6.png)

Plus each challenge doc will also have a new "version" field.

Please consider this new structure when working on this ticket (I've pushed the necessary data changes to both the dev and preview Firestore envs - in preview it'll only work for the challenge that's currently pinned there).

**Comment by Safi-Ullah** [comment]
> Plus each challenge doc will also have a new "version" field.

The version field will be cloned with the rest of the scorecard, right..?...even though it won't be displayed anywhere on the frontend.

**Comment by fenske** [comment]
> > Plus each challenge doc will also have a new "version" field.
> 
> 
> 
> The version field will be cloned with the rest of the scorecard, right..?...even though it won't be displayed anywhere on the frontend.

That's right. Although not directly displayed, good to copy it to know exactly which scorecard version each candidate got (could be useful for troubleshooting).

**Comment by fenske** [comment]
@Safi-Ullah I released it again and it worked this time. 🤷‍♂️ Can't explain what happened when I'd released it earlier today. 

But anyway. Good job! This is really going to simplify life for the hiring teams.

Now we kinda got a little discrepancy because the challenge library slideover still refers to the old scorecard in GitHub, but that's what we'll fix in the next ticket. 😃

What was your time investment this time, if I may ask?

**Comment by Safi-Ullah** [comment]
> What was your time investment this time, if I may ask?

Yeah, I spent around 15 hrs on this one.
