### ISSUE TITLE
Ability to filter candidates by language/technology

### ISSUE THREAD

**Issue by fenske** [fenske/devskills-app#37]
### User Story
Right now, it is very hard to know if a candidate has completed a test in one language/technology or another, via the devskills platform.

A language/technology filter on the candidate view would be super helpful.

### AC
It's possible to filter candidates by language/technology on the Candidates view.

**Comment by fenske** [comment]
@lhaynes23 And here's the best way to submit a Feature Request. 😊

**Comment by fenske** [comment]
@lhaynes23 I'll need to wrap my head around how to incorporate it best, but in the meantime, here's a workaround for you:

![CleanShot 2020-11-18 at 10 27 47](https://user-images.githubusercontent.com/1162212/99511752-f48b6800-2988-11eb-8756-5c2e5fe3fc62.gif)

You can add a so-called topic to each candidate's repository to signal what tech stack this assignment is about. You'll still need to navigate to the repo from your DevSkills console, but at least you'll be able to distinguish the assignments right from the topic list.

Would you think this would do?

**Comment by fenske** [comment]
@lhaynes23 It's out. 🎉 You can cover both marking tech stack and the review status with labels.

Here's a little demo: https://devskills.co/blog/new-feature-labels

**Comment by lhaynes23** [comment]
@fenske sorry for not replying sooner. Really nice to see this implementation. Good work!

Some small additions which would make this even nicer would be:

- The ability to filter candidates. I.e., get an overview of all candidates with the label Java, for example. A further iteration on this would be to add a filter for the different test levels for a Java candidate, for example.

- Changing the colour of the Approved, Rejected etc. labels to be green or red or orange depending on their status. E.g., if a candidate has not been approved nor rejected, they could assume the label *Pending* with the orange colour on the label; if *Approved*, the label is green; if *Rejected*, the label is red. 

Just some ideas that I think again would make the recruiters lives a lot easier :)

**Comment by fenske** [comment]
Insightful feedback, Lee. 💡 Thanks a lot for sharing! 

Though intuitive, let me still clarify a couple of things to make sure I get the use case right.

> I.e., get an overview of all candidates with the label Java, for example. A further iteration on this would be to add a filter for the different test levels for a Java candidate, for example.

Who'd be the main user (recruiters, reviewers, account owners, all)? In what situations would this be useful?

**Comment by lhaynes23** [comment]
@fenske good question. 

The main user would be the recruiter and it would be useful for the following reason: 

- Ability to make sure they know who they can or should present to the owner of a particular request. They may have different requests ongoing, where they are interviewing candidates across different languages. Hence it could be nice for them to get a focussed view. 

A case could be made for account owners too, as overtime we might want to get a greater idea on statistics, such as but not limited to:

- Number of candidates taking the test - broken down per level and language possibly;
- Number of candidates passing the tests - also broken down as per above;
- Redundant tests for our particular business and model.

**Comment by fenske** [comment]
I see. I've noted your feedback now. Good backlog items will come out of this for sure. ✅

Thanks again for sharing!

**Comment by fenske** [comment]
@lhaynes23 You can now filter candidates based on the criteria you specified above. Check out this announcement: https://devskills.co/blog/new-feature-candidate-filters.
