### ISSUE TITLE
Ability to see when a code reviewer has reviewed a candidate's code in the devskills platform

### ISSUE THREAD

**Issue by lhaynes23** [fenske/devskills-app#38]
Right now we can see if a code reviewer has reviewed someone's code by way of comments in the repo, and also any communication he/she has with a recruiter.

We can also see if a candidate has completed the test (and whether this was done successfully: green, red or grey circles placed next to the candidate's name accordingly). It would be nice if there were some kind of indication that the reviewer had completed making a review of the candidate's submitted test.

Perhaps some kind of icon or indeed the result published on a candidate's card on the candidate page in devskills, and the ability to filter by those reviewed and not reviewed, for example. 

Just a suggestion, but I think it would be a nice feature, mostly for the recruiter to be able to quickly see the code review result when this has been published.

**Comment by fenske** [comment]
@lhaynes23 I analyzed the data I had, and I can propose the following feature that I believe should address both this and #37.

It's called "labels".

 For each candidate, you can create a set of labels:

<img src="https://user-images.githubusercontent.com/1162212/99945152-6c380900-2d74-11eb-9943-7b650fae4c52.png" height="700">

Which will then appear on the Candidate dashboard and let the recruiter filter the candidates by those labels:

<img src="https://user-images.githubusercontent.com/1162212/99945221-870a7d80-2d74-11eb-996d-d904b5d63ed9.png" height="500">

There will also be a possibility to update the labels for any of your already invited candidates (e.g. to add the code review status).

Let me know what you think. 🙂

**Comment by lhaynes23** [comment]
@fenske this would certainly be a great help! I like your thinking! :)

**Comment by fenske** [comment]
Rolled out the instructions for how to mark an assignment as approved/rejected. Closing this issue.
