### ISSUE TITLE
Invite new team members from the app

### ISSUE THREAD

**Issue by fenske** [fenske/devskills-app#41]
### User Story
As a user on the Team account, I want to add team members to my DevSkills team account.

### AC
**GIVEN** A user is on the Team account
**WHEN** They need to add a team member to their account
**THEN** They can do it from within the DevSkills app.

**Comment by fenske** [comment]
# Grooming

## What to deal with

- [ ] How to tell if someone is on a Team+ subscription
- [ ] GitHub users can have multiple emails associated with their account. If the user has set a public email, then that's what ends up in Firebase. If not, then the primary one.
- [ ] Need a settings screen

**Comment by fenske** [comment]
Great job @Safi-Ullah ! It's in prod. 

Would you mind sharing your time investment for this task?

**Comment by Safi-Ullah** [comment]
> Would you mind sharing your time investment for this task?

Yeah, it took me around 19 hrs to get this task done.

**Comment by fenske** [comment]
Got it. Thanks!
