### ISSUE TITLE
Can't open the repository or whatever it is

### ISSUE THREAD

**Issue by mari-wine** [fenske/devskills-app#43]
When I click on a clickable link I see a 404 mistake.
So I can't see the candidate's completed tests.

Please, fix it :) Thanks!

**Comment by fenske** [comment]
Hi @mari-wine ! 👋 Try accepting your invite at https://github.com/37d7fcd0-f13b-4571-8fd3-fc12d70c7b7d.

**Comment by mari-wine** [comment]
Hi Anton!

Thanks a lot for your help! Everything is working now :)

Have a great day.


Regards,
Marina



вт, 1 дек. 2020 г. в 15:07, Anton Fenske <notifications@github.com>:
