### ISSUE TITLE
candidate's issue

### ISSUE THREAD

**Issue by Mariamtsv** [fenske/devskills-app#44]
Hi Anton,
My React Native candidate just sent me this:

<img width="378" alt="Screenshot 2020-12-01 at 18 19 22" src="https://user-images.githubusercontent.com/66784104/100768776-f0892c80-3403-11eb-8c7e-635f3d80c0a8.png">

![image](https://user-images.githubusercontent.com/66784104/100768536-abfd9100-3403-11eb-9f8f-4fa5e27b49e9.png)

Can you please help me with this?

million thanks
Maria

**Comment by fenske** [comment]
Hi @Mariamtsv . 👋

Before I reach out to the candidate, the assignment you referred is for Frontend developers but React Native is mobile dev.

So your candidate can't do React Native with this assignment, and the platform doesn't currently have coding challenges for Mobile dev.

Given this, are you still sure you want them to do this test?

**Comment by Mariamtsv** [comment]
Hi @fenske 
thank you so much for the quick reply. 
Now it's clear. I will send him a different assignment.

Btw, do you have plans to create assessments for mobile development as well?

**Comment by fenske** [comment]
It is on the roadmap, and you are for sure not the first person asking me this. 

I could release mobile challenges sooner but only without automated tests. So you'd need to fully rely on your code reviewers to do evaluation (which would be more work for them).

Would that be an acceptable scenario?

**Comment by Mariamtsv** [comment]
Definitely. Thank you for your work, Anton.
