### ISSUE TITLE
Deleting candidate from the list

### ISSUE THREAD

**Issue by kjnchka** [fenske/devskills-app#45]
Can we somehow delete the candidate from the list? 
The test was sent mistakenly to one of them
@fenske

**Comment by fenske** [comment]
For now, feel free to share a scorecard link here and I'll take care of it. 🙂

Will think about how to incorporate it in the app.

**Comment by Mariamtsv** [comment]
Hi Anton :)

Please see the link
https://github.com/37d7fcd0-f13b-4571-8fd3-fc12d70c7b7d/account-management-frontend-level-2-0.0.7-j3hi3a

Thank you for helping!

**Comment by fenske** [comment]
Done. ✅
