### ISSUE TITLE
Acces needed for our employee 

### ISSUE THREAD

**Issue by mari-wine** [fenske/devskills-app#46]
**Please, provide access to devskills.co for Islam Rustamov**
Islam Rustamov is our colleague and code reviewer. He's gonna be conducting code reviews. 

His contacts:

Github username: IslamRustam
Email: islam.rustam0v28et@gmail.com 

Thank you in advance!

**Comment by fenske** [comment]
Hi @mari-wine . Could you ask your colleague to sign-up at http://app.devskills.co/ first?

**Comment by fenske** [comment]
Also, a note. This repo is publicly available so it's not great for sharing personal data. I'll come up with a better procedure soon.

**Comment by mari-wine** [comment]
Hi Anton,

Thank you very much. Will do it now.
If we can simplify any process, it'd perfect :)



пт, 4 дек. 2020 г. в 15:38, Anton Fenske <notifications@github.com>:

**Comment by mari-wine** [comment]
Hi again,

Still not working. Islam cannot access the repo.

пт, 4 дек. 2020 г. в 15:39, Anton Fenske <notifications@github.com>:

**Comment by fenske** [comment]
Now I see that he signed up. 🙂 Will add him shortly.

**Comment by fenske** [comment]
Now. ✅

As usual, 

Accept the invite at https://github.com/37d7fcd0-f13b-4571-8fd3-fc12d70c7b7d
Log out and log in at http://app.devskills.co/.

**Comment by mari-wine** [comment]
Thanks!

Looks like everything's working now.

пт, 4 дек. 2020 г. в 16:37, Anton Fenske <notifications@github.com>:
